const moment = require("moment-timezone");
const fs = require("fs-extra");
const axios = require("axios");
const cheerio = require("cheerio");
const Canvas = require("canvas");
const https = require("https");
const agent = new https.Agent({ rejectUnauthorized: false });

module.exports = {
	config: {
		name: "moon",
		version: "1.5",
		author: "𝑨𝒔𝒊𝒇 𝑴𝒂𝒉𝒎𝒖𝒅",
		countDown: 5,
		role: 0,
		category: "🌠 Astronomy",
		description: {
			en: "🌙 View moon phase with beautiful canvas design"
		},
		guide: {
			en: "   {pn} [dd/mm/yyyy]"
				+ "\n   Example: {pn} 15/08/2023"
		}
	},

	langs: {
		en: {
			invalidDateFormat: "⚠️ | Please enter a valid date in DD/MM/YYYY format",
			error: "❌ | An error occurred while getting the moon image of %1",
			invalidDate: "⚠️ | %1 is not a valid date",
			caption: "🌙 | Moon phase on: %1\n"
		}
	},

	onStart: async function ({ args, message, getLang }) {
		try {
			const date = checkDate(args[0]);
			if (!date)
				return message.reply(getLang("invalidDateFormat"));
			
			const linkCrawl = `https://lunaf.com/lunar-calendar/${date}`;
			const html = await axios.get(linkCrawl, { httpsAgent: agent });
			const $ = cheerio.load(html.data);
			
			const href = $("figure img").attr("data-ezsrcset");
			const number = href.match(/phase-(\d+)\.png/)[1];
			const imgSrc = moonImages[Number(number)];
			const { data: imgSrcBuffer } = await axios.get(imgSrc, { responseType: "arraybuffer" });

			// Create canvas
			const canvas = Canvas.createCanvas(1000, 1200);
			const ctx = canvas.getContext("2d");
			
			// Draw gradient background
			const gradient = ctx.createLinearGradient(0, 0, 1000, 1200);
			gradient.addColorStop(0, "#0c1445");
			gradient.addColorStop(1, "#2c1a4d");
			ctx.fillStyle = gradient;
			ctx.fillRect(0, 0, canvas.width, canvas.height);
			
			// Draw stars
			ctx.fillStyle = "white";
			for (let i = 0; i < 150; i++) {
				const x = Math.random() * canvas.width;
				const y = Math.random() * canvas.height;
				const radius = Math.random() * 1.5;
				ctx.beginPath();
				ctx.arc(x, y, radius, 0, Math.PI * 2);
				ctx.fill();
			}
			
			// Draw moon image
			const moon = await Canvas.loadImage(imgSrcBuffer);
			const moonSize = 600;
			ctx.drawImage(
				moon, 
				(canvas.width - moonSize) / 2, 
				100, 
				moonSize, 
				moonSize
			);
			
			// Draw information box
			ctx.fillStyle = "rgba(255, 255, 255, 0.1)";
			ctx.globalCompositeOperation = "lighter";
			ctx.beginPath();
			ctx.roundRect(50, 750, 900, 400, 30);
			ctx.fill();
			
			// Reset composite operation
			ctx.globalCompositeOperation = "source-over";
			
			// Add text information
			ctx.font = "bold 40px 'Arial'";
			ctx.fillStyle = "#e0c3fc";
			ctx.textAlign = "center";
			ctx.fillText("LUNAR PHASE REPORT", canvas.width / 2, 820);
			
			ctx.font = "30px 'Arial'";
			ctx.fillStyle = "white";
			ctx.textAlign = "left";
			
			const infoLines = [
				`📅 Date: ${args[0]}`,
				`🌕 Phase: ${$($('h3').get()[0]).text()}`,
				`🌖 Visibility: ${$("#phimg > small").text()}`,
				`🔗 Source: lunaf.com`
			];
			
			let yPosition = 880;
			for (const line of infoLines) {
				ctx.fillText(line, 100, yPosition);
				yPosition += 60;
			}
			
			// Add decorative elements
			ctx.strokeStyle = "#8a4fff";
			ctx.lineWidth = 3;
			ctx.beginPath();
			ctx.moveTo(150, 780);
			ctx.lineTo(250, 780);
			ctx.stroke();
			
			ctx.beginPath();
			ctx.moveTo(750, 780);
			ctx.lineTo(850, 780);
			ctx.stroke();
			
			// Add watermark
			ctx.font = "20px 'Arial'";
			ctx.fillStyle = "rgba(255, 255, 255, 0.5)";
			ctx.textAlign = "right";
			ctx.fillText("Generated by Bot", canvas.width - 30, canvas.height - 30);
			
			// Save and send image
			const pathSave = __dirname + "/tmp/moonPhase.png";
			fs.writeFileSync(pathSave, canvas.toBuffer());
			
			message.reply({
				body: getLang("caption", args[0]) + "✨",
				attachment: fs.createReadStream(pathSave)
			}, () => fs.unlinkSync(pathSave));
		}
		catch (err) {
			console.error(err);
			message.reply(getLang("error", args[0] || ""));
		}
	}
};

// Helper functions
function checkDate(date) {
	const [day0, month0, year0] = (date || "").split('/');
	const day = (day0 || "").length == 1 ? "0" + day0 : day0;
	const month = (month0 || "").length == 1 ? "0" + month0 : month0;
	const year = year0 || "";
	const newDateFormat = year + "/" + month + "/" + day;
	return moment(newDateFormat, 'YYYY/MM/DD', true).isValid() ? newDateFormat : false;
}

// Register rounded rectangle function
Canvas.CanvasRenderingContext2D.prototype.roundRect = function (x, y, width, height, radius) {
	if (width < 2 * radius) radius = width / 2;
	if (height < 2 * radius) radius = height / 2;
	this.beginPath();
	this.moveTo(x + radius, y);
	this.arcTo(x + width, y, x + width, y + height, radius);
	this.arcTo(x + width, y + height, x, y + height, radius);
	this.arcTo(x, y + height, x, y, radius);
	this.arcTo(x, y, x + width, y, radius);
	this.closePath();
	return this;
};

// All 32 moon images included as requested
const moonImages = [
	'https://i.ibb.co/9shyYH1/moon-0.png',
	'https://i.ibb.co/vBXLL37/moon-1.png',
	'https://i.ibb.co/0QCKK9D/moon-2.png',
	'https://i.ibb.co/Dp62X2j/moon-3.png',
	'https://i.ibb.co/xFKCtfd/moon-4.png',
	'https://i.ibb.co/m4L533L/moon-5.png',
	'https://i.ibb.co/VmshdMN/moon-6.png',
	'https://i.ibb.co/4N7R2B2/moon-7.png',
	'https://i.ibb.co/C2k4YB8/moon-8.png',
	'https://i.ibb.co/F62wHxP/moon-9.png',
	'https://i.ibb.co/Gv6R1mk/moon-10.png',
	'https://i.ibb.co/0ZYY7Kk/moon-11.png',
	'https://i.ibb.co/KqXC5F5/moon-12.png',
	'https://i.ibb.co/BGtLpRJ/moon-13.png',
	'https://i.ibb.co/jDn7pPx/moon-14.png',
	'https://i.ibb.co/kykn60t/moon-15.png',
	'https://i.ibb.co/qD4LFLs/moon-16.png',
	'https://i.ibb.co/qJm9gcQ/moon-17.png',
	'https://i.ibb.co/yYFYZx9/moon-18.png',
	'https://i.ibb.co/8bc7vpZ/moon-19.png',
	'https://i.ibb.co/jHG7DKs/moon-20.png',
	'https://i.ibb.co/5WD18Rn/moon-21.png',
	'https://i.ibb.co/3Y06yHM/moon-22.png',
	'https://i.ibb.co/4T8Zdfy/moon-23.png',
	'https://i.ibb.co/n1CJyP4/moon-24.png',
	'https://i.ibb.co/zFwJRqz/moon-25.png',
	'https://i.ibb.co/gVBmMCW/moon-26.png',
	'https://i.ibb.co/hRY89Hn/moon-27.png',
	'https://i.ibb.co/7C13s7Z/moon-28.png',
	'https://i.ibb.co/2hDTwB4/moon-29.png',
	'https://i.ibb.co/Rgj9vpj/moon-30.png',
	'https://i.ibb.co/s5z0w9R/moon-31.png'
];
