const DIG = require("discord-image-generation");
const fs = require("fs-extra");
const path = require("path");
const { createCanvas, loadImage } = require("canvas");

module.exports.config = {
  name: "putin",
  version: "2.1",
  hasPermssion: 0,
  credits: "𝑨𝒔𝒊𝒇 𝑴𝒂𝒉𝒎𝒖𝒅",
  description: "Create Putin meeting meme with tagged user (or yourself)",
  category: "meme",
  usages: "[@mention]",
  cooldowns: 5,
  dependencies: {
    "discord-image-generation": "",
    "fs-extra": "",
    "canvas": ""
  }
};

module.exports.onStart = async function ({ api, event, args, Users }) {
  try {
    const { threadID, messageID, senderID, mentions } = event;

    let mentionID, name;

    if (mentions && Object.keys(mentions).length) {
      mentionID = Object.keys(mentions)[0];
      name = mentions[mentionID].replace("@", "");
    } else {
      mentionID = senderID;
      const userInfo = await Users.getNameUser(senderID);
      name = userInfo || "Unknown User";
    }

    const avatarURL = await Users.getAvatarUrl(mentionID);

    if (!avatarURL) {
      return api.sendMessage("❌ | Failed to fetch avatar!", threadID, messageID);
    }

    // Generate Putin meme
    const imgBuffer = await new DIG.Poutine().getImage(avatarURL);
    const filePath = path.join(__dirname, `/cache/putin_${mentionID}.png`);

    // Create stylish frame using canvas
    const bg = await loadImage(imgBuffer);
    const canvas = createCanvas(bg.width, bg.height + 70);
    const ctx = canvas.getContext("2d");

    // Gradient background
    const gradient = ctx.createLinearGradient(0, 0, canvas.width, 0);
    gradient.addColorStop(0, "#0d47a1");
    gradient.addColorStop(1, "#b71c1c");
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Draw Putin meme image
    ctx.drawImage(bg, 0, 70, bg.width, bg.height);

    // Add stylish title text
    ctx.font = 'bold 30px "Arial"';
    ctx.fillStyle = "#FFD700";
    ctx.textAlign = "center";
    ctx.fillText(`PUTIN MEETS ${name.toUpperCase()}`, canvas.width / 2, 45);

    // Add Russian flag emoji decoration
    ctx.font = '40px "Segoe UI Emoji"';
    ctx.fillText("🇷🇺 ★ 🇷🇺 ★ 🇷🇺", canvas.width / 2, 100);

    // Save final image
    const out = fs.createWriteStream(filePath);
    const stream = canvas.createPNGStream();
    stream.pipe(out);

    await new Promise((resolve, reject) => {
      out.on("finish", resolve);
      out.on("error", reject);
    });

    // Send result
    api.sendMessage(
      {
        body: `🇷🇺✨ Putin is officially meeting with ${name}!\n👤 Target: ${name}\n🎨 Generated by: ${this.config.credits}`,
        attachment: fs.createReadStream(filePath)
      },
      threadID,
      () => fs.unlinkSync(filePath),
      messageID
    );

  } catch (error) {
    console.error(error);
    api.sendMessage("❌ | Error generating meme. Please try again later.", event.threadID, event.messageID);
  }
};
