const DIG = require("discord-image-generation");
const fs = require("fs-extra");
const path = require("path");
const { createCanvas, loadImage } = require("canvas");

module.exports.config = {
  name: "putin",
  version: "2.0",
  author: "𝑨𝒔𝒊𝒇 𝑴𝒂𝒉𝒎𝒖𝒅",
  countDown: 5,
  role: 0,
  shortDescription: "Create Putin meeting meme",
  longDescription: "Generate a meme showing Putin meeting with a tagged user 🇷🇺",
  category: "meme",
  guide: {
    en: "{pn} [@mention]"
  },
  dependencies: {
    "discord-image-generation": "",
    "fs-extra": "",
    "canvas": ""
  }
};

module.exports.run = async function ({ api, event, args, Users }) {
  try {
    const { threadID, messageID, mentions } = event;
    
    if (!mentions || !Object.keys(mentions).length) {
      return api.sendMessage("🇷🇺 | Please tag someone to create the Putin meeting meme!", threadID, messageID);
    }

    const mentionID = Object.keys(mentions)[0];
    const name = mentions[mentionID].replace("@", "");
    const avatarURL = await Users.getAvatarUrl(mentionID);
    
    if (!avatarURL) {
      return api.sendMessage("❌ | Failed to fetch user's avatar!", threadID, messageID);
    }

    // Generate Putin meme
    const imgBuffer = await new DIG.Poutine().getImage(avatarURL);
    const filePath = path.join(__dirname, `/cache/putin_${mentionID}.png`);
    
    // Create stylish frame using canvas
    const bg = await loadImage(imgBuffer);
    const canvas = createCanvas(bg.width, bg.height + 70);
    const ctx = canvas.getContext('2d');
    
    // Add gradient background
    const gradient = ctx.createLinearGradient(0, 0, canvas.width, 0);
    gradient.addColorStop(0, '#0d47a1');
    gradient.addColorStop(1, '#b71c1c');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    // Draw Putin image
    ctx.drawImage(bg, 0, 70, bg.width, bg.height);
    
    // Add stylish text
    ctx.font = 'bold 30px "Arial"';
    ctx.fillStyle = '#FFD700';
    ctx.textAlign = 'center';
    ctx.fillText(`PUTIN MEETS ${name.toUpperCase()}`, canvas.width/2, 45);
    
    // Add Russian flag emoji decoration
    ctx.font = '40px "Segoe UI Emoji"';
    ctx.fillText('🇷🇺 ★ 🇷🇺 ★ 🇷🇺', canvas.width/2, 100);

    // Save final image
    const out = fs.createWriteStream(filePath);
    const stream = canvas.createPNGStream();
    stream.pipe(out);
    
    await new Promise((resolve, reject) => {
      out.on('finish', resolve);
      out.on('error', reject);
    });

    // Send result
    api.sendMessage({
      body: `🇷🇺 | Putin is meeting with ${name}!\n> Generated by: ${this.config.author}`,
      attachment: fs.createReadStream(filePath)
    }, threadID, () => fs.unlinkSync(filePath), messageID);

  } catch (error) {
    console.error(error);
    api.sendMessage("❌ | Error generating meme. Please try again later.", threadID, messageID);
  }
};
