const axios = require('axios');
const { createCanvas, loadImage } = require('canvas');
const fs = require('fs');
const path = require('path');

module.exports.config = {
  name: "quranverse",
  aliases: ["verse", "quran", "ayah"],
  version: "2.0",
  author: "𝑨𝒔𝒊𝒇 𝑴𝒂𝒉𝒎𝒖𝒅",
  countDown: 10,
  role: 0,
  shortDescription: {
    en: "Get Quran verses with translations and audio"
  },
  longDescription: {
    en: "Fetch Quran verses with multiple translations and optional audio recitation"
  },
  category: "islam",
  guide: {
    en: "{pn} [random] - Get random verse\n{pn} audio - Get verse with recitation\n{pn} [surah]:[verse] - Get specific verse\n{pn} lang [code] - Set translation language (en/ur/ar/bn)"
  },
  dependencies: {
    "axios": "",
    "canvas": ""
  },
  envConfig: {}
};

module.exports.langs = {
  en: "English",
  ur: "Urdu",
  ar: "Arabic",
  bn: "Bengali"
};

async function createVerseImage(verseData, language) {
  const width = 800;
  const height = 600;
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext('2d');

  // Background gradient
  const gradient = ctx.createLinearGradient(0, 0, width, height);
  gradient.addColorStop(0, '#0c1e25');
  gradient.addColorStop(1, '#1d4a5d');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, width, height);

  // Decorative elements
  ctx.fillStyle = 'rgba(255, 255, 255, 0.05)';
  for (let i = 0; i < 20; i++) {
    ctx.beginPath();
    ctx.arc(
      Math.random() * width,
      Math.random() * height,
      Math.random() * 10 + 5,
      0,
      Math.PI * 2
    );
    ctx.fill();
  }

  // Title
  ctx.font = 'bold 40px "Segoe UI"';
  ctx.fillStyle = '#f1c40f';
  ctx.textAlign = 'center';
  ctx.fillText('🌙 Quran Verse 🌙', width / 2, 70);

  // Surah info
  ctx.font = '28px "Segoe UI"';
  ctx.fillStyle = '#e67e22';
  ctx.fillText(`${verseData.surahName} (${verseData.surahNameTranslation})`, width / 2, 130);
  
  ctx.font = '22px "Segoe UI"';
  ctx.fillStyle = '#ecf0f1';
  ctx.fillText(`Surah ${verseData.surahNumber}:${verseData.verseNumber} | ${verseData.revelationPlace}`, width / 2, 170);

  // Arabic text
  ctx.font = 'bold 36px "Traditional Arabic"';
  ctx.fillStyle = '#2ecc71';
  ctx.fillText(verseData.arabic1, width / 2, 260);

  // Translation header
  ctx.font = 'italic 26px "Segoe UI"';
  ctx.fillStyle = '#3498db';
  ctx.fillText(`${this.langs[language]} Translation:`, width / 2, 330);

  // Translation text
  const translation = verseData[language] || verseData.english;
  ctx.font = '24px "Segoe UI"';
  ctx.fillStyle = '#ecf0f1';
  wrapText(ctx, translation, width / 2, 380, 700, 32);

  // Footer
  ctx.font = '18px "Segoe UI"';
  ctx.fillStyle = '#bdc3c7';
  ctx.fillText('Generated by GoatBot • Credits: 𝑨𝒔𝒊𝒇 𝑴𝒂𝒉𝒎𝒖𝒅', width / 2, height - 30);

  // Save image
  const imagePath = path.join(__dirname, '..', 'tmp', `quran_${Date.now()}.png`);
  const buffer = canvas.toBuffer('image/png');
  fs.writeFileSync(imagePath, buffer);
  
  return imagePath;
}

function wrapText(ctx, text, x, y, maxWidth, lineHeight) {
  const words = text.split(' ');
  let line = '';
  let testLine;
  let metrics;
  
  for (let n = 0; n < words.length; n++) {
    testLine = line + words[n] + ' ';
    metrics = ctx.measureText(testLine);
    
    if (metrics.width > maxWidth && n > 0) {
      ctx.fillText(line, x, y);
      line = words[n] + ' ';
      y += lineHeight;
    } else {
      line = testLine;
    }
  }
  ctx.fillText(line, x, y);
}

module.exports.run = async function ({ api, event, args }) {
  try {
    const action = args[0]?.toLowerCase();
    const wantsAudio = action === 'audio';
    const wantsRandom = !action || action === 'random';
    const wantsLanguage = action === 'lang' && args[1];
    const wantsSpecific = /^\d+:\d+$/.test(action);

    if (wantsLanguage) {
      const langCode = args[1].toLowerCase();
      if (this.langs[langCode]) {
        global.quranLanguage = langCode;
        return api.sendMessage(`✅ Translation language set to ${this.langs[langCode]}`, event.threadID);
      }
      return api.sendMessage(`❌ Invalid language. Available: ${Object.keys(this.langs).join(', ')}`, event.threadID);
    }

    const language = global.quranLanguage || 'en';
    const surahsResponse = await axios.get("https://quranapi.pages.dev/api/surah.json");
    if (!surahsResponse.data) throw new Error("Couldn't fetch surah list");

    const surahs = surahsResponse.data;
    let surahNumber, verseNumber;

    if (wantsSpecific) {
      [surahNumber, verseNumber] = action.split(':').map(Number);
    } else {
      surahNumber = surahs[Math.floor(Math.random() * surahs.length)].number;
      const surahDetail = await axios.get(`https://quranapi.pages.dev/api/${surahNumber}.json`);
      if (!surahDetail.data) throw new Error("Couldn't fetch surah details");
      verseNumber = Math.floor(Math.random() * surahDetail.data.english.length) + 1;
    }

    const verseResponse = await axios.get(`https://quranapi.pages.dev/api/${surahNumber}/${verseNumber}.json`);
    if (!verseResponse.data) throw new Error("Couldn't fetch verse details");

    const verseData = verseResponse.data;
    verseData.surahNumber = surahNumber;
    verseData.verseNumber = verseNumber;

    // Create canvas image
    const imagePath = await createVerseImage(verseData, language);
    
    let messageBody = `📖 ${verseData.surahName} (${verseData.surahNameTranslation})\n` +
                     `Surah ${surahNumber}:${verseNumber} | ${verseData.revelationPlace}\n\n` +
                     `"${verseData.arabic1}"\n\n` +
                     `*${this.langs[language]} Translation:*\n${verseData[language] || verseData.english}`;

    if (wantsAudio && verseData.audio) {
      const reciters = Object.values(verseData.audio);
      messageBody += `\n\n🎧 Available Reciters:\n`;
      reciters.forEach((reciter, i) => {
        messageBody += `${i+1}. ${reciter.reciter}\n`;
      });
      messageBody += `\nReply with number to hear recitation`;

      global.audioOptions = {
        reciters: reciters,
        verseInfo: `${verseData.surahName} ${surahNumber}:${verseNumber}`
      };
    }

    api.sendMessage({
      body: messageBody,
      attachment: fs.createReadStream(imagePath)
    }, event.threadID, () => fs.unlinkSync(imagePath));

  } catch (error) {
    console.error(error);
    api.sendMessage("❌ An error occurred while fetching Quran verse. Please try again later.", event.threadID);
  }
};

module.exports.handleReply = async function ({ api, event }) {
  try {
    if (!global.audioOptions || !event.body) return;

    const selectedNumber = parseInt(event.body);
    const { reciters, verseInfo } = global.audioOptions;

    if (isNaN(selectedNumber)) return;
    if (selectedNumber < 1 || selectedNumber > reciters.length) {
      return api.sendMessage("❌ Invalid selection. Please reply with a number from the list.", event.threadID);
    }

    const selectedReciter = reciters[selectedNumber - 1];
    api.sendMessage({
      body: `🎧 Playing ${verseInfo} - ${selectedReciter.reciter}`,
      attachment: await global.utils.getStreamFromURL(selectedReciter.url)
    }, event.threadID);

    delete global.audioOptions;

  } catch (error) {
    console.error(error);
    api.sendMessage("❌ Failed to play the recitation. Please try again.", event.threadID);
  }
};
